"""
Module for storing supported trailer sites
"""

from .algolia_trailers import ALGOLIA_SITES, ALGOLIA_SPECIAL_SITES
from .aylo_trailers import AYLO_DOMAINS

# Sites that use generic HTML parsing and aren't in other module lists
HTML_ONLY_SITES = {
    "18yearsold.com",
    "40ozbounce.com",
    "adultprime.com",
    "alexlegend.com",
    "allherluv.com",
    "anal4k.com",
    "analized.com",
    "analvids.com",
    "badoinkvr.com",
    "badteenspunished.com",
    "baeb.com",
    "bbcpie.com",
    "castingcouch-x.com",
    "castingcouchx.com",
    "caughtmycoach.com",
    "cheatingsis.com",
    "clips4sale.com",
    "cockcompetition.com",
    "creepypa.com",
    "crueltyparty.com",
    "cum4k.com",
    "cumshotsurprise.com",
    "cumswappingsis.com",
    "daddyslilangel.com",
    "deepthroatlove.com",
    "detentiongirls.com",
    "disgraced18.com",
    "driverxxx.com",
    "dyked.com",
    "eurohumpers.com",
    "exotic4k.com",
    "facials4k.com",
    "familyporn.tv",
    "familyswap.xxx",
    "fantasyhd.com",
    "flexiblepositions.com",
    "foxxedup.com",
    "freakmobmedia.com",
    "freaksofboob.com",
    "freaksofcock.com",
    "ftvmilfs.com",
    "fuckedhard18.com",
    "getyourkneesdirty.com",
    "girlcum.com",
    "girlgirl.com",
    "holed.com",
    "hollyrandall.com",
    "hussiepass.com",
    "interracialpass.com",
    "jamesdeen.com",
    "julesjordan.com",
    "legalporno.com",
    "lubed.com",
    "manyvids.com",
    "missax.com",
    "mom4k.com",
    "momcum.com",
    "momsteachsex.com",
    "myfamilypies.com",
    "myveryfirsttime.com",
    "nannyspy.com",
    "nubilefilms.com",
    "nubiles-casting.com",
    "nubiles-porn.com",
    "nubiles.net",
    "nubileset.com",
    "nubilesunscripted.com",
    "passion-hd.com",
    "petiteballerinasfucked.com",
    "petitehdporn.com",
    "pornmastermind.com",
    "pornpros.com",
    "povd.com",
    "princesscum.com",
    "publichandjobs.com",
    "puremature.com",
    "realitysis.com",
    "rickysroom.com",
    "sexlikereal.com",
    "smashed.xxx",
    "spyfam.com",
    "stepsiblingscaught.com",
    "strippers4k.com",
    "swallowed.com",
    "swallowsalon.com",
    "teacherfucksteens.com",
    "teamskeet.com",
    "theassfactory.com",
    "thepovgod.com",
    "tiny4k.com",
    "twistedvisual.com",
    "vrbangers.com",
    "vrcosplayx.com",
    "vrhush.com",
    "archive.org",
    "wetvr.com",
    "youngermommy.com",
}

# Generate the comprehensive set from all sources
SUPPORTED_TRAILER_SITES = (
    HTML_ONLY_SITES
    | set(ALGOLIA_SITES)
    | set(ALGOLIA_SPECIAL_SITES.keys())
    | AYLO_DOMAINS
)
