name: "🐛 Bug Report"
description: Create a report to help us improve Vexxx
title: "[Bug]: "
labels:
  - bug
  - triage
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
        Please fill out this form as completely as possible to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: |
        When I click "XYZ", the application crashes or shows an error...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: |
        The video should start playing...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: |
        The player showed a black screen and an error message appeared in the console...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Logs
      description: If applicable, add screenshots or logs to help explain your problem. Paste images or drag/drop them here.
      placeholder: |
        [Error Log]
        ...
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Vexx Version
      description: What version of Vexx are you running? (e.g. v0.26.1, v0.27.0-43-gabcdef)
      placeholder: v0.26.2
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Desktop/Server OS
      description: What OS is the Vexxx server running on? (e.g. Windows 11, Ubuntu 22.04, Docker)
      placeholder: Windows 11
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: What browser are you using to access Vexxx? (e.g. Chrome, Firefox, Safari)
      placeholder: Chrome 120
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How critical is this bug?
      options:
        - Critical (Crash / Data Loss)
        - Major (Feature Broken)
        - Minor (Annoyance / Visual Glitch)
    validations:
      required: true
