export type LanguageOption = {
  value: string;
  label: string;
};

export const LANGUAGE_OPTIONS: readonly LanguageOption[] = [
  { value: "af-ZA", label: "Afrikaans (Preview)" },
  { value: "bg-BG", label: "Bulgarian (Preview)" },
  { value: "bn-BD", label: "বাংলা (বাংলাদেশ) (Preview)" },
  { value: "ca-ES", label: "Catalan (Preview)" },
  { value: "cs-CZ", label: "Čeština (Česko)" },
  { value: "da-DK", label: "Dansk (Danmark)" },
  { value: "de-DE", label: "Deutsch (Deutschland)" },
  { value: "en-GB", label: "English (United Kingdom)" },
  { value: "en-US", label: "English (United States)" },
  { value: "et-EE", label: "Eesti" },
  { value: "fa-IR", label: "فارسی (ایران) (Preview)" },
  { value: "fi-FI", label: "Suomi" },
  { value: "fr-FR", label: "Français (France)" },
  { value: "hi-IN", label: "हिन्दी (Preview)" },
  { value: "hr-HR", label: "Hrvatski (Preview)" },
  { value: "id-ID", label: "Indonesian (Preview)" },
  { value: "hu-HU", label: "Magyar (Preview)" },
  { value: "it-IT", label: "Italiano" },
  { value: "ja-JP", label: "日本語 (日本)" },
  { value: "ko-KR", label: "한국어 (대한민국)" },
  { value: "lv-LV", label: "Latviešu (Preview)" },
  { value: "lt-LT", label: "Lithuanian (Preview)" },
  { value: "nb-NO", label: "Norsk bokmål" },
  { value: "nn-NO", label: "Nynorsk (Preview)" },
  { value: "nl-NL", label: "Nederlands (Nederland)" },
  { value: "pl-PL", label: "Polski" },
  { value: "pt-BR", label: "Português (Brasil)" },
  { value: "ro-RO", label: "Română (Preview)" },
  { value: "ru-RU", label: "Русский (Россия)" },
  { value: "es-ES", label: "Español (España)" },
  { value: "sk-SK", label: "Slovenčina (Preview)" },
  { value: "sv-SE", label: "Svenska" },
  { value: "tr-TR", label: "Türkçe (Türkiye)" },
  { value: "th-TH", label: "ภาษาไทย (ไทย)" },
  { value: "uk-UA", label: "Ukrainian (Україна)" },
  { value: "ur-PK", label: "Urdu (Preview)" },
  { value: "vi-VN", label: "Tiếng Việt (Preview)" },
  { value: "zh-TW", label: "繁體中文 (台灣)" },
  { value: "zh-CN", label: "简体中文 (中国)" },
] as const;
